package com.xinto.mauth.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val MothPurpleLight = lightColorScheme(
    primary = Color(0xFF804D7A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD7F5),
    onPrimaryContainer = Color(0xFF340832),
    secondary = Color(0xFF6D5869),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF7DAEF),
    onSecondaryContainer = Color(0xFF271624),
    tertiary = Color(0xFF825345),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDBD1),
    onTertiaryContainer = Color(0xFF321208),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF7F9),
    onBackground = Color(0xFF201A1E),
    surface = Color(0xFFFFF7F9),
    onSurface = Color(0xFF201A1E),
    surfaceVariant = Color(0xFFEEDEE7),
    onSurfaceVariant = Color(0xFF4E444B),
    outline = Color(0xFF80747C),
    outlineVariant = Color(0xFFD1C2CB),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF352E33),
    inverseOnSurface = Color(0xFFFAEDF4),
    inversePrimary = Color(0xFFF1B3E6),
    surfaceDim = Color(0xFFE3D7DD),
    surfaceBright = Color(0xFFFFF7F9),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDF0F7),
    surfaceContainer = Color(0xFFF7EBF1),
    surfaceContainerHigh = Color(0xFFF1E5EB),
    surfaceContainerHighest = Color(0xFFECDFE5),
)
val MothPurpleDark = darkColorScheme(
    primary = Color(0xFFF1B3E6),
    onPrimary = Color(0xFF4C1F49),
    primaryContainer = Color(0xFF653661),
    onPrimaryContainer = Color(0xFFFFD7F5),
    secondary = Color(0xFFDABFD2),
    onSecondary = Color(0xFF3D2B3A),
    secondaryContainer = Color(0xFF554151),
    onSecondaryContainer = Color(0xFFF7DAEF),
    tertiary = Color(0xFFF5B8A7),
    onTertiary = Color(0xFF4C261B),
    tertiaryContainer = Color(0xFF663C2F),
    onTertiaryContainer = Color(0xFFFFDBD1),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF171216),
    onBackground = Color(0xFFECDFE5),
    surface = Color(0xFF171216),
    onSurface = Color(0xFFECDFE5),
    surfaceVariant = Color(0xFF4E444B),
    onSurfaceVariant = Color(0xFFD1C2CB),
    outline = Color(0xFF9A8D95),
    outlineVariant = Color(0xFF4E444B),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFECDFE5),
    inverseOnSurface = Color(0xFF352E33),
    inversePrimary = Color(0xFF804D7A),
    surfaceDim = Color(0xFF171216),
    surfaceBright = Color(0xFF3E373C),
    surfaceContainerLowest = Color(0xFF120D11),
    surfaceContainerLow = Color(0xFF201A1E),
    surfaceContainer = Color(0xFF241E22),
    surfaceContainerHigh = Color(0xFF2F282D),
    surfaceContainerHighest = Color(0xFF3A3338),
)
